import logging
import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt

logger = logging.getLogger(__name__)


def create_1st_stage_charts(stats_df):
    width = 0.35

    logger.info("Plotting clusters per strain")
    set_labels_font_size()
    sorted_stats = stats_df.sort_values('total_clusters', ascending=False).reset_index(drop=True)
    plt.bar(sorted_stats.index.values, sorted_stats['total_clusters'])
    plt.xlabel("strains #")
    plt.ylabel("clusters #")
    plt.title("strains to clusters bar chart")
    plt.savefig('total_clusters_by_strain.pdf', format="pdf")
    plt.close()

    logger.info("Plotting missing core clusters per strain")
    set_labels_font_size()
    sorted_stats = stats_df.sort_values('missing_core', ascending=False).reset_index(drop=True)
    plt.bar(sorted_stats.index.values, sorted_stats['missing_core'])
    plt.xlabel("strains #")
    plt.ylabel("% of missing core clusters")
    plt.title("strains to missing core clusters bar chart")
    plt.savefig('missing_core_clusters_by_strain.pdf', format="pdf")
    plt.close()

    logger.info("Plotting singleton clusters per strain")
    set_labels_font_size()
    sorted_stats = stats_df.sort_values('singletons', ascending=False).reset_index(drop=True)
    plt.bar(sorted_stats.index.values, sorted_stats['singletons'])
    plt.xlabel("strains #")
    plt.ylabel("singleton clusters #")
    plt.title("strains to singleton clusters bar chart")
    plt.savefig('singleton_clusters_by_strain.pdf', format="pdf")
    plt.close()

    logger.info("Plotting pseudogenes per strain")
    set_labels_font_size()
    sorted_stats = stats_df.sort_values('pseudogenes', ascending=False).reset_index(drop=True)
    plt.bar(sorted_stats.index.values, sorted_stats['pseudogenes'])
    plt.xlabel("strains #")
    plt.ylabel("pseudogenes #")
    plt.title("strains to pseudogenes bar chart")
    plt.savefig('pseudogenes_by_strain.pdf', format="pdf")
    plt.close()

    logger.info("Plotting contigs per strain")
    set_labels_font_size()
    sorted_stats = stats_df.sort_values('contigs', ascending=False).reset_index(drop=True)
    plt.bar(sorted_stats.index.values, sorted_stats['contigs'])
    plt.xlabel("strains #")
    plt.ylabel("contigs #")
    plt.title("strains to contigs bar chart")
    plt.savefig('contigs_by_strain.pdf', format="pdf")
    plt.close()

    logger.info("Plotting contigs VS singletons per strain")
    set_labels_font_size()
    sorted_stats = stats_df.sort_values('contigs', ascending=False).reset_index(drop=True)
    chart1 = plt.bar(sorted_stats.index.values, sorted_stats['contigs'], width)
    chart2 = plt.bar(sorted_stats.index.values + width, sorted_stats['singletons'], width)
    plt.xlabel("Strains #")
    plt.ylabel("Contigs # / Singletons #")
    plt.title("Contigs VS Singletons per strain")
    plt.legend((chart1[0], chart2[0]), ("Contigs #", "Singletons #"))
    plt.savefig('contigs_vs_singletons_by_strain.pdf', format="pdf")
    plt.close()

    logger.info("Plotting contigs VS missing core % per strain")
    set_labels_font_size()
    sorted_stats = stats_df.sort_values('contigs', ascending=False).reset_index(drop=True)
    chart1 = plt.bar(sorted_stats.index.values, sorted_stats['contigs'], width)
    chart2 = plt.bar(sorted_stats.index.values + width, sorted_stats['missing_core'], width)
    plt.xlabel("Strains #")
    plt.ylabel("Contigs # / Missing Core %")
    plt.title("Contigs VS Missing Core % per strain")
    plt.legend((chart1[0], chart2[0]), ("Contigs #", "Missing Core %"))
    plt.savefig('contigs_vs_missing_core_by_strain.pdf', format="pdf")
    plt.close()

    logger.info("Plotting contigs VS pseudogenes per strain")
    set_labels_font_size()
    sorted_stats = stats_df.sort_values('contigs', ascending=False).reset_index(drop=True)
    chart1 = plt.bar(sorted_stats.index.values, sorted_stats['pseudogenes'], width)
    chart2 = plt.bar(sorted_stats.index.values + width, sorted_stats['contigs'], width)
    plt.xlabel("Strains #")
    plt.ylabel("Contigs # / Pseudogenes #")
    plt.title("Contigs VS Pseudogenes per strain")
    plt.legend((chart1[0], chart2[0]), ("Pseudogenes #", "Contigs #"))
    plt.savefig('contigs_vs_pseudogenes_by_strain.pdf', format="pdf")
    plt.close()

    logger.info("Plotting singletons VS missing core % per strain")
    set_labels_font_size()
    sorted_stats = stats_df.sort_values('singletons', ascending=False).reset_index(drop=True)
    chart1 = plt.bar(sorted_stats.index.values, sorted_stats['singletons'], width)
    chart2 = plt.bar(sorted_stats.index.values + width, sorted_stats['missing_core'], width)
    plt.xlabel("Strains #")
    plt.ylabel("Singletons # / Missing Core %")
    plt.title("Singletons VS Missing core % per strain")
    plt.legend((chart1[0], chart2[0]), ("Singletons #", "Missing Core %"))
    plt.savefig('singletons_vs_missing_core_by_strain.pdf', format="pdf")
    plt.close()

    logger.info("Plotting pseudogenes VS missing core % per strain")
    set_labels_font_size()
    sorted_stats = stats_df.sort_values('pseudogenes', ascending=False).reset_index(drop=True)
    chart1 = plt.bar(sorted_stats.index.values, sorted_stats['pseudogenes'], width)
    chart2 = plt.bar(sorted_stats.index.values + width, sorted_stats['missing_core'], width)
    plt.xlabel("Strains #")
    plt.ylabel("Pseudogenes # / Missing Core %")
    plt.title("strains to pseudogenes VS missing core bar chart")
    plt.legend((chart1[0], chart2[0]), ("Pseudogenes #", "Missing Core %"))
    plt.savefig('pseudogenes_vs_missing_core_by_strain.pdf', format="pdf")
    plt.close()

    logger.info("Plotting pseudogenes VS singletons per strain")
    set_labels_font_size()
    sorted_stats = stats_df.sort_values('pseudogenes', ascending=False).reset_index(drop=True)
    chart1 = plt.bar(sorted_stats.index.values, sorted_stats['pseudogenes'], width)
    chart2 = plt.bar(sorted_stats.index.values + width, sorted_stats['singletons'], width)
    plt.xlabel("Strains #")
    plt.ylabel("Pseudogenes # / Singletons #")
    plt.title("strains to pseudogenes VS singletons bar chart")
    plt.legend((chart1[0], chart2[0]), ("Pseudogenes #", "Singletons #"))
    plt.savefig('pseudogenes_vs_singletons_by_strain.pdf', format="pdf")
    plt.close()


def set_labels_font_size():
    ax = plt.subplot()
    for label in (ax.get_xticklabels() + ax.get_yticklabels()):
        label.set_fontsize(3)
